import { Module } from '@nestjs/common';

import {
  ParyatechCompanyCreateManyPreQueryHook,
  ParyatechCompanyCreateOnePreQueryHook,
  ParyatechCompanyUpdateManyPreQueryHook,
  ParyatechCompanyUpdateOnePreQueryHook,
  ParyatechCommercialAgreementCreateManyPreQueryHook,
  ParyatechCommercialAgreementCreateOnePreQueryHook,
  ParyatechCommercialAgreementUpdateManyPreQueryHook,
  ParyatechCommercialAgreementUpdateOnePreQueryHook,
  ParyatechOpportunityCreateManyPreQueryHook,
  ParyatechOpportunityCreateOnePreQueryHook,
  ParyatechOpportunityUpdateManyPreQueryHook,
  ParyatechOpportunityUpdateOnePreQueryHook,
  ParyatechPersonCreateManyPreQueryHook,
  ParyatechPersonCreateOnePreQueryHook,
  ParyatechPersonUpdateManyPreQueryHook,
  ParyatechPersonUpdateOnePreQueryHook,
  ParyatechSharedExceptionCreateManyPreQueryHook,
  ParyatechSharedExceptionCreateOnePreQueryHook,
  ParyatechSharedExceptionUpdateManyPreQueryHook,
  ParyatechSharedExceptionUpdateOnePreQueryHook,
  ParyatechSupportCaseCreateManyPreQueryHook,
  ParyatechSupportCaseCreateOnePreQueryHook,
  ParyatechSupportCaseUpdateManyPreQueryHook,
  ParyatechSupportCaseUpdateOnePreQueryHook,
  ParyatechSupportReceiptCreateManyPreQueryHook,
  ParyatechSupportReceiptCreateOnePreQueryHook,
  ParyatechSupportReceiptUpdateManyPreQueryHook,
  ParyatechSupportReceiptUpdateOnePreQueryHook,
} from 'src/modules/paryatech-crm/query-hooks/paryatech-protected-field.pre-query.hook';

@Module({
  providers: [
    ParyatechCompanyCreateManyPreQueryHook,
    ParyatechCompanyCreateOnePreQueryHook,
    ParyatechCompanyUpdateManyPreQueryHook,
    ParyatechCompanyUpdateOnePreQueryHook,
    ParyatechCommercialAgreementCreateManyPreQueryHook,
    ParyatechCommercialAgreementCreateOnePreQueryHook,
    ParyatechCommercialAgreementUpdateManyPreQueryHook,
    ParyatechCommercialAgreementUpdateOnePreQueryHook,
    ParyatechOpportunityCreateManyPreQueryHook,
    ParyatechOpportunityCreateOnePreQueryHook,
    ParyatechOpportunityUpdateManyPreQueryHook,
    ParyatechOpportunityUpdateOnePreQueryHook,
    ParyatechPersonCreateManyPreQueryHook,
    ParyatechPersonCreateOnePreQueryHook,
    ParyatechPersonUpdateManyPreQueryHook,
    ParyatechPersonUpdateOnePreQueryHook,
    ParyatechSharedExceptionCreateManyPreQueryHook,
    ParyatechSharedExceptionCreateOnePreQueryHook,
    ParyatechSharedExceptionUpdateManyPreQueryHook,
    ParyatechSharedExceptionUpdateOnePreQueryHook,
    ParyatechSupportCaseCreateManyPreQueryHook,
    ParyatechSupportCaseCreateOnePreQueryHook,
    ParyatechSupportCaseUpdateManyPreQueryHook,
    ParyatechSupportCaseUpdateOnePreQueryHook,
    ParyatechSupportReceiptCreateManyPreQueryHook,
    ParyatechSupportReceiptCreateOnePreQueryHook,
    ParyatechSupportReceiptUpdateManyPreQueryHook,
    ParyatechSupportReceiptUpdateOnePreQueryHook,
  ],
})
export class ParyatechQueryHookModule {}
