export const PARYATECH_CRM_OBJECT_NAMES = [
  'company',
  'person',
  'outreachEvent',
  'sharedException',
  'crmOperatingPolicy',
] as const;

export const REQUIRED_FIELDS_BY_OBJECT: Record<
  (typeof PARYATECH_CRM_OBJECT_NAMES)[number],
  readonly string[]
> = {
  company: [
    'agencyLifecycle',
    'recordOwner',
    'isSuppressed',
    'reservationStatus',
    'reservationClaimant',
    'reservationClaimedAt',
    'reservationExpiresAt',
    'reservationReleaseReason',
    'firstAttemptedAt',
    'firstProviderAcceptedAt',
    'firstPendingUnknownAt',
    'firstContactedAt',
    'firstEngagedAt',
  ],
  person: ['isSuppressed'],
  outreachEvent: [
    'eventReference',
    'agency',
    'contact',
    'operator',
    'channel',
    'initiatedAt',
    'outcome',
    'providerEvidenceKey',
    'providerObservedAt',
    'evidenceSummary',
    'nextAction',
    'nextActionAt',
    'pendingExpiresAt',
    'reasonedRetry',
    'reservationSnapshot',
  ],
  sharedException: [
    'exceptionReference',
    'capability',
    'affectedObject',
    'affectedRecordId',
    'status',
    'lastTrustedState',
    'owner',
    'dueAt',
    'escalation',
    'evidence',
    'resolvedAt',
    'resumeReason',
    'resumedAt',
  ],
  crmOperatingPolicy: [
    'active',
    'businessCalendar',
    'pendingUnknownMaxBusinessDays',
    'reservationIntervalMinutes',
  ],
};
