export const GUARDED_TRANSITION_OBJECT_NAMES = [
  'company',
  'person',
  'opportunity',
  'commercialAgreement',
  'supportCase',
  'supportReceipt',
  'sharedException',
  'crmOperatingPolicy',
] as const;

export const GUARDED_TRANSITION_REQUIRED_FIELDS: Record<
  (typeof GUARDED_TRANSITION_OBJECT_NAMES)[number],
  readonly string[]
> = {
  company: [
    'agencyLifecycle',
    'agencyDisposition',
    'isSuppressed',
    'suppressionReason',
    'suppressedAt',
    'suppressionClearedAt',
    'suppressionClearanceReason',
  ],
  person: [
    'company',
    'isSuppressed',
    'suppressionReason',
    'suppressedAt',
    'suppressionClearedAt',
    'suppressionClearanceReason',
  ],
  opportunity: [
    'company',
    'contacts',
    'owner',
    'products',
    'stage',
    'amount',
    'nextAction',
    'nextActionAt',
    'demoScheduledAt',
    'demoOccurredAt',
    'demoAttendees',
    'demoOutcome',
    'proposalDeliveredAt',
    'commercialDecisionContext',
    'lossReason',
    'lossDecisionAt',
    'revisitAt',
    'primarySource',
    'influencedSources',
    'trialState',
    'trialReason',
    'trialOwner',
    'trialStartsAt',
    'trialEndsAt',
    'trialSuccessCriteria',
    'trialExpectedDecision',
    'trialExtensionReason',
    'trialOutcome',
    'agreement',
  ],
  commercialAgreement: [
    'agreementReference',
    'agency',
    'sourceOpportunity',
    'products',
    'term',
    'startsAt',
    'endsAt',
    'grossBooked',
    'currency',
    'commercialException',
    'paymentState',
    'amountCollected',
    'waivedAmount',
    'refundedOrReversedAmount',
    'netCollected',
    'evidenceSource',
    'evidenceType',
    'evidenceVerifier',
    'evidenceObservedAt',
    'evidenceRecordedAt',
    'evidenceState',
    'renewalState',
    'renewalAt',
    'renewalOwner',
    'renewalNextAction',
    'renewalNextActionAt',
    'activationState',
    'activationConfirmedAt',
    'activationConfirmer',
    'adoptionState',
    'adoptionEvidence',
    'adoptionObservedAt',
    'paryatechOsCommercialReference',
  ],
  supportCase: [
    'caseReference',
    'subject',
    'summary',
    'channel',
    'priority',
    'sourceReceivedAt',
    'responseTargetAt',
    'owner',
    'status',
    'escalation',
    'disposition',
    'firstSubstantiveResponseAt',
    'resolution',
    'agency',
    'contact',
    'product',
    'agreement',
  ],
  supportReceipt: [
    'receiptKey',
    'channel',
    'providerOrSourceId',
    'sourceReceivedAt',
    'payloadHash',
    'case',
    'receiptDisposition',
  ],
  sharedException: [
    'exceptionReference',
    'capability',
    'affectedObject',
    'affectedRecordId',
    'status',
    'lastTrustedState',
    'owner',
    'dueAt',
    'escalation',
    'evidence',
    'resolvedAt',
    'resumeReason',
    'resumedAt',
  ],
  crmOperatingPolicy: ['active', 'businessCalendar'],
};
